### ISSUE TITLE
V0.2 - Ability to remove "Product" from product table

### ISSUE THREAD

**Issue by suvel** [suvel/kannaku_sollu#3]
**TODO**

- [x] Add Unique Id for each product that is being added

- [x] Added "Remove" button to the product table.

- [x] Make the "Remove" button functional

- [x] Add icon to the button and update the style.
